### ISSUE TITLE
Framevuerk-builder postinstall fails

### ISSUE THREAD

**Issue by Savallator** [framevuerk/framevuerk-builder#2]
When installing, the postinstall fails with
`
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

> framevuerk-builder@2.0.7 postinstall yyy\node_modules\framevuerk-builder
> npm install -C ./deps-dir -s && node cleanup.js

yyy\node_modules\framevuerk-builder\deps-dir\framevuerk-builder -> yyy\node_modules\framevuerk-builder\deps-dir\node_modules\framevuerk-builder\index.js
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\watchpack-chokidar2\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN framevuerk@3.0.0-beta28 requires a peer of vue@>= 2.2.0 < 3 but none is installed. You must install peer dependencies yourself.
npm WARN framevuerk-builder@2.0.7 requires a peer of framevuerk@>=2.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 4294963238
npm ERR! framevuerk-builder@2.0.7 postinstall: `npm install -C ./deps-dir -s && node cleanup.js`
npm ERR! Exit status 4294963238
npm ERR!
npm ERR! Failed at the framevuerk-builder@2.0.7 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2020-05-25T23_05_46_689Z-debug.log

`

However, the file has no Helpful information:
`
19340 warn framevuerk-builder@2.0.7 requires a peer of framevuerk@>=2.0.0 but none is installed. You must install peer dependencies yourself.
19341 verbose stack Error: framevuerk-builder@2.0.7 postinstall: `npm install -C ./deps-dir -s && node cleanup.js`
19341 verbose stack Exit status 4294963238
19341 verbose stack     at EventEmitter.<anonymous> (C:\Users\xxx\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
19341 verbose stack     at EventEmitter.emit (events.js:311:20)
19341 verbose stack     at ChildProcess.<anonymous> (C:\Users\xxx\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
19341 verbose stack     at ChildProcess.emit (events.js:311:20)
19341 verbose stack     at maybeClose (internal/child_process.js:1021:16)
19341 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
19342 verbose pkgid framevuerk-builder@2.0.7

...

19346 verbose node v12.16.1
19347 verbose npm  v6.14.5
19348 error code ELIFECYCLE
19349 error errno 4294963238
19350 error framevuerk-builder@2.0.7 postinstall: `npm install -C ./deps-dir -s && node cleanup.js`
19350 error Exit status 4294963238
19351 error Failed at the framevuerk-builder@2.0.7 postinstall script.
19351 error This is probably not a problem with npm. There is likely additional logging output above.
19352 verbose exit [ 4294963238, true ]
`
It is strange that it says the Peer Dependency is not there, since i clearly have it installed. But i dont really understand the point of that post-install script. It looks like it is used to install some dependencys, but in fact i suspect it tries to install framevuerk-builder a second time? 

I already tried cleaning cache etc...
The same error occurs in a test setup outside of my project, and there it makes the following folder structure:

`C:\Users\xxx\Downloads\framevuerk-builder-2.0.7\package\deps-dir\node_modules\framevuerk-builder\deps-dir\node_modules`

**Comment by sabond** [comment]
I am encountering this error, too

**Comment by nainemom** [comment]
Please give it an another shot using next patch version `2.0.8`.
